"""initial schema

Revision ID: 17186652a814
Revises: 
Create Date: 2026-09-03 16:26:00.113246+09:00
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = '17186652a814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_user_id', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_users_provider_uid')
    )
    op.create_table('api_access_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_access_logs_created_at'), 'api_access_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_access_logs_kind'), 'api_access_logs', ['kind'], unique=False)
    op.create_index(op.f('ix_api_access_logs_path'), 'api_access_logs', ['path'], unique=False)
    op.create_index(op.f('ix_api_access_logs_user_id'), 'api_access_logs', ['user_id'], unique=False)
    op.create_table('route_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('personalized', sa.Boolean(), nullable=False),
    sa.Column('explored', sa.Boolean(), nullable=False),
    sa.Column('propensities', sa.JSON(), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('origin_name', sa.String(length=200), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lng', sa.Float(), nullable=False),
    sa.Column('dest_name', sa.String(length=200), nullable=False),
    sa.Column('profile', sa.String(length=32), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weather_mode', sa.String(length=16), nullable=False),
    sa.Column('weather', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('elapsed_ms', sa.Float(), nullable=True),
    sa.Column('engine_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_requests_created_at'), 'route_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_route_requests_profile'), 'route_requests', ['profile'], unique=False)
    op.create_index(op.f('ix_route_requests_user_id'), 'route_requests', ['user_id'], unique=False)
    op.create_table('user_policies',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('updates', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('engine_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('profile', sa.String(length=32), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('corridor_nodes', sa.Integer(), nullable=False),
    sa.Column('corridor_edges', sa.Integer(), nullable=False),
    sa.Column('blocked_edges', sa.Integer(), nullable=False),
    sa.Column('snap_origin_m', sa.Float(), nullable=True),
    sa.Column('snap_destination_m', sa.Float(), nullable=True),
    sa.Column('aco_iterations', sa.Integer(), nullable=False),
    sa.Column('aco_ants_completed', sa.Integer(), nullable=False),
    sa.Column('aco_ants_failed', sa.Integer(), nullable=False),
    sa.Column('aco_stopped_by', sa.String(length=32), nullable=False),
    sa.Column('aco_elapsed_ms', sa.Float(), nullable=True),
    sa.Column('ga_enabled', sa.Boolean(), nullable=False),
    sa.Column('ga_generations', sa.Integer(), nullable=False),
    sa.Column('ga_elapsed_ms', sa.Float(), nullable=True),
    sa.Column('archive_size', sa.Integer(), nullable=False),
    sa.Column('routes_returned', sa.Integer(), nullable=False),
    sa.Column('engine_elapsed_ms', sa.Float(), nullable=True),
    sa.Column('backend_elapsed_ms', sa.Float(), nullable=True),
    sa.Column('shade_status', sa.String(length=32), nullable=False),
    sa.Column('weather_flags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['route_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_runs_created_at'), 'engine_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_engine_runs_profile'), 'engine_runs', ['profile'], unique=False)
    op.create_index(op.f('ix_engine_runs_request_id'), 'engine_runs', ['request_id'], unique=False)
    op.create_table('policy_updates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('route_id', sa.String(length=32), nullable=False),
    sa.Column('shown_rank', sa.Integer(), nullable=False),
    sa.Column('engine_rank', sa.Integer(), nullable=True),
    sa.Column('explored', sa.Boolean(), nullable=False),
    sa.Column('updates_after', sa.Integer(), nullable=False),
    sa.Column('weights_before', sa.JSON(), nullable=True),
    sa.Column('weights_after', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['route_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_updates_created_at'), 'policy_updates', ['created_at'], unique=False)
    op.create_index(op.f('ix_policy_updates_user_id'), 'policy_updates', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('place_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('edge_id', sa.BigInteger(), nullable=True),
    sa.Column('edge_kind', sa.String(length=16), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['route_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_kind'), 'reports', ['kind'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('route_choices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('route_id', sa.String(length=32), nullable=False),
    sa.Column('shown_rank', sa.Integer(), nullable=False),
    sa.Column('propensity', sa.Float(), nullable=True),
    sa.Column('learned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['route_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_choices_created_at'), 'route_choices', ['created_at'], unique=False)
    op.create_index(op.f('ix_route_choices_request_id'), 'route_choices', ['request_id'], unique=False)
    op.create_index(op.f('ix_route_choices_user_id'), 'route_choices', ['user_id'], unique=False)
    op.create_table('route_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('cautions', sa.JSON(), nullable=True),
    sa.Column('total_duration_min', sa.Float(), nullable=False),
    sa.Column('walk_distance_m', sa.Float(), nullable=False),
    sa.Column('transfers', sa.Integer(), nullable=False),
    sa.Column('generalized_cost_s', sa.Float(), nullable=True),
    sa.Column('engine_rank', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['route_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_results_request_id'), 'route_results', ['request_id'], unique=False)
    op.create_table('edge_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edge_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_overrides_active'), 'edge_overrides', ['active'], unique=False)
    op.create_index(op.f('ix_edge_overrides_created_at'), 'edge_overrides', ['created_at'], unique=False)
    op.create_index(op.f('ix_edge_overrides_edge_id'), 'edge_overrides', ['edge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edge_overrides_edge_id'), table_name='edge_overrides')
    op.drop_index(op.f('ix_edge_overrides_created_at'), table_name='edge_overrides')
    op.drop_index(op.f('ix_edge_overrides_active'), table_name='edge_overrides')
    op.drop_table('edge_overrides')
    op.drop_index(op.f('ix_route_results_request_id'), table_name='route_results')
    op.drop_table('route_results')
    op.drop_index(op.f('ix_route_choices_user_id'), table_name='route_choices')
    op.drop_index(op.f('ix_route_choices_request_id'), table_name='route_choices')
    op.drop_index(op.f('ix_route_choices_created_at'), table_name='route_choices')
    op.drop_table('route_choices')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_kind'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_policy_updates_user_id'), table_name='policy_updates')
    op.drop_index(op.f('ix_policy_updates_created_at'), table_name='policy_updates')
    op.drop_table('policy_updates')
    op.drop_index(op.f('ix_engine_runs_request_id'), table_name='engine_runs')
    op.drop_index(op.f('ix_engine_runs_profile'), table_name='engine_runs')
    op.drop_index(op.f('ix_engine_runs_created_at'), table_name='engine_runs')
    op.drop_table('engine_runs')
    op.drop_table('user_policies')
    op.drop_index(op.f('ix_route_requests_user_id'), table_name='route_requests')
    op.drop_index(op.f('ix_route_requests_profile'), table_name='route_requests')
    op.drop_index(op.f('ix_route_requests_created_at'), table_name='route_requests')
    op.drop_table('route_requests')
    op.drop_index(op.f('ix_api_access_logs_user_id'), table_name='api_access_logs')
    op.drop_index(op.f('ix_api_access_logs_path'), table_name='api_access_logs')
    op.drop_index(op.f('ix_api_access_logs_kind'), table_name='api_access_logs')
    op.drop_index(op.f('ix_api_access_logs_created_at'), table_name='api_access_logs')
    op.drop_table('api_access_logs')
    op.drop_table('users')
    op.drop_table('place_searches')
    # ### end Alembic commands ###
